name: kate-chat

services:
  redis:
    image: redislabs/redistimeseries
    container_name: kate-chat-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  backend:
    scale: 3
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "4000-4003:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    networks:
      - kate-chat-network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kate-chat-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_WS_URL=ws://localhost:4000
    networks:
      - kate-chat-network
    env_file:
      - ./frontend/.env

networks:
  kate-chat-network:
    driver: bridge

volumes:
  db_data: {}
  redis-data: {}
