name: kate-chat

services:
  postgres:
    image: postgres:15-alpine
    container_name: kate-chat-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=katechat
      - POSTGRES_PASSWORD=katechat
      - POSTGRES_DB=katechat
    networks:
      - kate-chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U katechat"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey
    container_name: kate-chat-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - kate-chat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    container_name: kate-chat-localstack
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    networks:
      - kate-chat-network
    environment:
      - PERSIST_DEFAULT=0
      - PERSIST_DYNAMODB=1
      - PERSIST_S3=1
    volumes:
      - ./config/init-s3.py:/etc/localstack/init/ready.d/init-s3.py  # ready hook
      - localstack-data:/persisted-data


  backend:
    scale: 3
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
      - localstack
    expose:
      - "4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_TYPE=postgres
      - DB_URL=postgres://katechat:katechat@postgres:5432/katechat
      - REDIS_URL=redis://redis:6379
      - CALLBACK_URL_BASE=http://katechat.dev.com/api
      - FRONTEND_URL=http://katechat.dev.com
      - ALLOWED_ORIGINS=http://katechat.dev.com
      # S3 storage configuration
      - S3_ENDPOINT=http://localstack:4566
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY_ID=localstack
      - S3_SECRET_ACCESS_KEY=localstack
      - S3_FILES_BUCKET_NAME=katechatdevfiles

    networks:
      - kate-chat-network
    env_file:
      - ./backend/.env

  backend-rust:
    build:
      context: ./backend-rust
      dockerfile: Dockerfile
    container_name: kate-chat-backend-rust
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    networks:
      - kate-chat-network
    
  nginx:
    image: nginx:alpine
    container_name: kate-chat-nginx
    ports:
      - "80:80"
    environment:
      - API_PORT=4000
      - WS_PORT=4000
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - kate-chat-network

networks:
  kate-chat-network:
    driver: bridge

volumes:
  postgres-data: {}
  redis-data: {}
  localstack-data: {}
