# Error monitoring: alert on HTTP 5xx responses served through the ALB.
#
# Two sources are covered:
#   - HTTPCode_Target_5XX_Count — 500s returned by the application itself
#   - HTTPCode_ELB_5XX_Count    — 5xx generated by the ALB (502/503/504:
#     no healthy targets, timeouts, connection failures)
#
# Alarm notifications go to an SNS topic with one email subscription per
# address in var.error_monitoring_recipients. Note: each subscription must be
# confirmed once via the link AWS mails to the recipient.

resource "aws_sns_topic" "error_monitoring" {
  name = "${var.project_name}-${var.environment}-error-monitoring"

  tags = {
    Name = "${var.project_name}-${var.environment}-error-monitoring"
  }
}

resource "aws_sns_topic_subscription" "error_monitoring_email" {
  for_each = toset(var.error_monitoring_recipients)

  topic_arn = aws_sns_topic.error_monitoring.arn
  protocol  = "email"
  endpoint  = each.value
}

resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name          = "${var.project_name}-${var.environment}-target-5xx"
  alarm_description   = "Application returned 5xx responses through the ALB (${var.project_name} ${var.environment})"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = var.error_monitoring_period_seconds
  evaluation_periods  = 1
  threshold           = var.error_monitoring_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  # The metric is simply absent while no errors occur — that's healthy.
  treat_missing_data = "notBreaching"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
  }

  alarm_actions = [aws_sns_topic.error_monitoring.arn]
  ok_actions    = [aws_sns_topic.error_monitoring.arn]

  tags = {
    Name = "${var.project_name}-${var.environment}-target-5xx"
  }
}

resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "${var.project_name}-${var.environment}-alb-5xx"
  alarm_description   = "ALB generated 5xx responses — unhealthy/unreachable targets or timeouts (${var.project_name} ${var.environment})"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = var.error_monitoring_period_seconds
  evaluation_periods  = 1
  threshold           = var.error_monitoring_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
  }

  alarm_actions = [aws_sns_topic.error_monitoring.arn]
  ok_actions    = [aws_sns_topic.error_monitoring.arn]

  tags = {
    Name = "${var.project_name}-${var.environment}-alb-5xx"
  }
}
